# -*- coding: utf-8 -*-
"""Copy of Website-ui

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159SNGpfKRoHoP0kIDO0iernwiEmr8IqG
"""

#pip install streamlit

# app.py

import streamlit as st

companies_by_domain = {
    "Technology": [
        "Amazon", "Google", "Microsoft", "Meta", "Apple",
        "Intel", "Qualcomm", "VMware", "IBM", "Oracle"
    ],
    "Finance": [
        "JPMorgan", "Goldman Sachs", "Citigroup", "Capital One", "Stripe",
        "PayPal", "Mastercard", "Visa", "UBS", "Fidelity"
    ],
    "Healthcare": [
        "UnitedHealth", "Pfizer", "IQVIA", "Cerner", "CVS Health",
        "Moderna", "GE Healthcare", "Roche", "Thermo Fisher", "AbbVie"
    ],
    "Consulting": [
        "Cognizant", "TCS", "Accenture", "Infosys", "Capgemini",
        "EY", "Deloitte", "HCL", "PwC", "Wipro"
    ],
    "Less Competitive": [
        "Databricks", "Snowflake", "DataRobot", "Flatiron Health", "Tiger Analytics",
        "Zest AI", "Clarify Health", "Health Catalyst", "Amplitude", "Alteryx"
    ]
}

st.title("🌎 H-1B Sponsoring Companies Explorer")

domain = st.selectbox("Select a Domain", list(companies_by_domain.keys()))

st.subheader(f"Top Companies in {domain}")
for company in companies_by_domain[domain]:
    st.markdown(f"✅ {company}")





